worksheets <- fs::path("_site", "activities", "tbd_tbd_analysis-review.pdf")
output <- fs::path("_site", "activities", "analysis.pdf")
combined_pdf <- fs::file_temp(ext = "pdf")
combined_pdf <- qpdf::pdf_combine(c(worksheets, output), combined_pdf)
fs::file_copy(combined_pdf, worksheets, overwrite = TRUE)
